version: 2.1

parameters:
  run-backend-workflow:
    type: boolean
    default: false
  image-tag: 
    type: string
    default: "latest"

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build_backend:
    executor: docker/machine
    steps:
      - checkout
      - docker/build:
          docker-context: backend
          path: ./backend
          image: $DOCKER_USER/demo-flask-backend
          tag: $CIRCLE_BUILD_NUM

  publish_backend:
    executor: docker/machine
    steps:
      - checkout
      - docker/build:
          docker-context: backend
          path: ./backend
          image: $DOCKER_USER/demo-flask-backend
          tag: $CIRCLE_BUILD_NUM
      - docker/check:
          docker-password: DOCKER_PASS
          docker-username: DOCKER_USER
      - docker/push:
          image: $DOCKER_USER/demo-flask-backend
          tag: $CIRCLE_BUILD_NUM


workflows:
  backend_workflow:
    when:
      <<pipeline.parameters.run-backend-workflow>>
    jobs:
      - build_backend:
          filters:
            branches:
              ignore: main
      - publish_backend:
          filters:
            branches:
              only: main