version: 2.1

parameters:
  run-backend-workflow:
    type: boolean
    default: false
  image-tag: 
    type: string
    default: "latest"

orbs:
  docker: circleci/docker@2.4.0

commands:
  build_backend:
    steps:
      - checkout
      - setup_remote_docker
      - docker/build:
          docker-context: backend
          path: ./backend
          image: $DOCKER_USER/demo-flask-backend
          tag: $CIRCLE_BUILD_NUM
  publish_backend:
    steps:
      - docker/check:
          docker-password: DOCKER_PASS
          docker-username: DOCKER_USER
      - docker/push:
          image: $DOCKER_USER/demo-flask-backend
          tag: $CIRCLE_BUILD_NUM

jobs:
  build_backend_job:
    executor: docker/docker
    steps:
      - build_backend

  publish_backend_job:
    executor: docker/docker
    steps:
      - build_backend
      - publish_backend

workflows:
  backend_workflow:
    when:
      <<pipeline.parameters.run-backend-workflow>>
    jobs:
      - build_backend_job:
          filters:
            branches:
              ignore: main
      - publish_backend_job:
          filters:
            branches:
              only: main