version: 2.1

parameters:
  run-frontend-workflow:
    type: boolean 
    default: false
  image-tag: 
    type: string
    default: "latest"

orbs:
  docker: circleci/docker@2.4.0


commands:
  build_frontend:
    steps:
      - checkout
      - docker/build:
          docker-context: frontend
          path: ./frontend
          image: $DOCKER_USER/demo-react-frontend
          tag: $CIRCLE_BUILD_NUM
  publish_frontend:
    steps:
      - docker/check:
          docker-password: DOCKER_PASS
          docker-username: DOCKER_USER
      - docker/push:
          image: $DOCKER_USER/demo-react-frontend
          tag: $CIRCLE_BUILD_NUM

jobs:
  build_frontend_job:
    executor: docker/docker
    steps:
      - build_frontend

  publish_frontend_job:
    executor: docker/machine
    steps:
      - build_frontend
      - publish_frontend


workflows:
  frontend_workflow:
    when:
      <<pipeline.parameters.run-frontend-workflow>>
    jobs:
      - build_frontend_job:
          filters:
            branches:
              ignore: main
      - publish_frontend_job:
          filters:
            branches:
              only: main