version: 2.1

parameters:
  run-backend-workflow:
    type: boolean
    default: false
  run-frontend-workflow:
    type: boolean 
    default: false
  image-tag: 
    type: string
    default: "latest"

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build_frontend:
    executor: docker/machine
    steps:
      - checkout
      - run:
          name: check the pwd and change dir
          command: |
            ls
            cd frontend
            ls
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
          attach-at: './'

  publish_frontend:
    executor: docker/machine
    steps:
      - checkout
      - attach_workspace:
          at: .
      - docker/check
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME



workflows:
  build_frontend_workflow:
    when:
      <<pipeline.parameters.run-frontend-workflow>>
    jobs:
      - build_frontend
      # - publish_frontend:
      #     requires:
      #       - build_frontend
      #     filters:
      #       branches:
      #         only: main