version: 2.1

parameters:
  run-backend-workflow:
    type: boolean
    default: false
  run-frontend-workflow:
    type: boolean 
    default: false
  image-tag: 
    type: string
    default: "latest"

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build_frontend:
    executor: docker/machine
    steps:
      - checkout
      - docker/build:
          docker-context: frontend
          path: ./frontend
          image: $DOCKER_USER/demo-react-frontend
          tag: $CIRCLE_BUILD_NUM
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  publish_frontend:
    executor: docker/machine
    steps:
      - attach_workspace:
          at: .
      # - docker/build:
      #     docker-context: frontend
      #     path: ./frontend
      #     image: $DOCKER_USER/demo-react-frontend
      #     tag: $CIRCLE_BUILD_NUM
      - docker/check:
          docker-password: DOCKER_PASS
          docker-username: DOCKER_USER
      - docker/push:
          image: $DOCKER_USER/demo-react-frontend
          tag: $CIRCLE_BUILD_NUM


workflows:
  build_frontend_workflow:
    when:
      <<pipeline.parameters.run-frontend-workflow>>
    jobs:
      - build_frontend
      - publish_frontend:
          requires:
            - build_frontend
          filters:
            branches:
              only: main