version: 2.1

parameters:
  run-backend-workflow:
    type: boolean
    default: false
  run-frontend-workflow:
    type: boolean 
    default: false
  image-tag: 
    type: string
    default: "latest"

  

orbs:
  docker: circleci/docker@2.4.0

jobs:
  build_frontend:
    executor: docker/machine
    steps:
      - checkout
      - docker/build:
          docker-context: frontend
          path: ./frontend
          image: $DOCKER_USER/demo-react-frontend
          tag: <<pipeline.parameters.image-tag>>
          attach-at: .

  publish_frontend:
    executor: docker/machine
    steps:
      - checkout
      - attach_workspace:
          at: .
      - docker/check:
          docker-password: DOCKER_PASS
          docker-username: DOCKER_USER
      - docker/push:
          image: $DOCKER_USER/demo-react-frontend
          tag: <<pipeline.parameters.image-tag>>


workflows:
  build_frontend_workflow:
    when:
      <<pipeline.parameters.run-frontend-workflow>>
    jobs:
      - build_frontend
      - publish_frontend:
          requires:
            - build_frontend
          filters:
            branches:
              only: main